ET-133 set staff role for lti
CredoReference/edx-platform pull request #16
Opened 2017-08-09 17:39 UTC by sruhela

When users log in through LTI, recognize they are Staff and give them staff permissions.

2017-08-09 21:29 UTC, dmitry-viskov requested changes
From the task description:
> Make sure instructor responses are excluded from reports (required for IMS certification)

i don't understand this condition. What reports are referring to? Today all reports include all answers from all users (students / instructors / admins / etc)

2017-08-09 21:29 UTC, dmitry-viskov commented on lms/djangoapps/lti_provider/users.py
> +                if 'Staff' in lti_role or 'Instructor' in lti_role or 'Administrator' in lti_role:
It is global permissions. As I understand you should use course permissions (see `CourseStaffRole`):
https://github.com/CredoReference/edx-platform/blob/integration-ficus/common/djangoapps/student/roles.py#L222

2017-08-09 21:29 UTC, dmitry-viskov commented on lms/djangoapps/lti_provider/views.py
> +    authenticate_lti_user(request, params['user_id'], params['roles'], lti_consumer, lti_params)
`roles` may not be transferred - you should predict this case

2017-08-09 21:33 UTC, dpowell commented
We will (in a future enchantment) want an option in Insights to exclude results from staff and instructors but the first step here is when launched via LTI as an instructor create a user with that role on the course team so that they get the instructor view of our course.

2017-08-09 21:34 UTC, dpowell commented on lms/djangoapps/lti_provider/users.py
> +                if 'Staff' in lti_role or 'Instructor' in lti_role or 'Administrator' in lti_role:
Agreed.

2017-08-10 19:34 UTC, sruhela commented on lms/djangoapps/lti_provider/views.py
> +    authenticate_lti_user(request, params['user_id'], params['roles'], lti_consumer, lti_params)
Right now roles is a required parameter for the launch and if the role is unrecognized we just allow them to log in as a user. Should that be different?

2017-08-10 19:57 UTC, dpowell commented on lms/djangoapps/lti_provider/views.py
> +    authenticate_lti_user(request, params['user_id'], params['roles'], lti_consumer, lti_params)
Agree, no role or an unrecognized role gets you a normal (student) user.

I think @dmitry-Viskov's concern was that if the `roles` key is not present in params, it'll blow up. You can use `params.get('roles')` instead, which will return `None` if the key is not found.

2017-08-11 10:28 UTC, dmitry-viskov commented on lms/djangoapps/lti_provider/views.py
> +    if 'Staff' in roles or 'Administrator' in roles:
Looks too complicated. I may suggest that such statement will be enough:
```
CourseStaffRole(course_key).add_users(user)
```

2017-08-11 10:29 UTC, dmitry-viskov commented on lms/djangoapps/lti_provider/views.py
> +    authenticate_lti_user(request, params['user_id'], params['roles'], lti_consumer, lti_params)
Yes. I mean `params.get('roles')`

2017-08-11 10:31 UTC, dmitry-viskov commented on lms/djangoapps/lti_provider/views.py
> +    if 'Instructor' in roles or 'Administrator' in roles:
'Instructor' is Course Admin
'Staff' is Course Staff

May be I'm wrong but we need to clarify this question. What roles are allowed. I may suggest that only 'Staff' (that is Course Staff)

2017-08-11 13:19 UTC, sruhela commented on lms/djangoapps/lti_provider/views.py
> +    if 'Instructor' in roles or 'Administrator' in roles:
'Instructor' is the only one required for the certification, so I just left 'staff' and 'instructor' for now.

2017-08-31 13:53 UTC, dmitry-viskov approved these changes

2017-08-31 13:54 UTC, merged